kind = "web"
previewPath = "/barakat-admin"
title = "Barakat Admin"
version = "1.0.0"
id = "artifacts/barakat-admin"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/barakat-admin" ]
localPort = 24430

[services.development]
run = "pnpm --filter @workspace/barakat-admin run dev"

[services.env]
PORT = "24430"
BASE_PATH = "/barakat-admin"
